server:
  port: 8081
spring:    
  application:
    name: ea-project
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost/cs544?verifyServerCertificate=false&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Chicago
=======
    url: jdbc:mysql://localhost:3306/cs544
>>>>>>> 617526f3c1e236cc93ba514de262fb4f175294a4
    username: ea
    password: ea123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect